export const IpcChannels = {
  configLoad: "config:load",
  configSave: "config:save",
  clipboardReadForTerminal: "clipboard:read-for-terminal",
  clipboardWriteText: "clipboard:write-text",
  permissionsEnsureTerminalPaste: "permissions:ensure-terminal-paste",
  dialogSelectFolder: "dialog:select-folder",
  dialogConfirm: "dialog:confirm",
  terminalCreate: "terminal:create",
  terminalWrite: "terminal:write",
  terminalResize: "terminal:resize",
  terminalKill: "terminal:kill",
  terminalAttach: "terminal:attach",
  terminalRestart: "terminal:restart",
  terminalReplay: "terminal:replay",
  terminalSetStreaming: "terminal:set-streaming",
  terminalIsBusy: "terminal:is-busy",
  terminalData: "terminal:data",
  terminalExit: "terminal:exit",
  appCommand: "app:command",
  gitRpc: "git:rpc",
  gitData: "git:data",
  imageRpc: "image:rpc",
  browserOpenExternal: "browser:open-external",
} as const;

export type IpcChannel = (typeof IpcChannels)[keyof typeof IpcChannels];
