//! Narrow task-preview policy.  This is deliberately not a general HTTP proxy.

use crate::config;
use rusqlite::params;
use std::{
    net::{IpAddr, Ipv4Addr, SocketAddr},
    path::Path,
};

pub fn approve(data_dir: &Path, task_id: &str, port: u16) -> Result<(), String> {
    if !safe_task_id(task_id) {
        return Err("preview task id is invalid".into());
    }
    if port == 0 {
        return Err("preview port is invalid".into());
    }
    let mut conn = config::connection_at(&config::db_path_in(data_dir).map_err(|e| e.to_string())?)
        .map_err(|e| e.to_string())?;
    // Keep the readiness check and grant insert in one write transaction.  Otherwise a task can
    // be tombstoned between the two statements and retain a port grant that was never valid.
    let tx = conn.transaction().map_err(|e| e.to_string())?;
    let ready: bool = tx.query_row(
        "SELECT EXISTS(SELECT 1 FROM tasks t JOIN task_provisioning p ON p.task_id=t.id WHERE t.id=?1 AND t.tombstoned_at IS NULL AND p.state='ready')",
        params![task_id], |row| row.get(0),
    ).map_err(|e| e.to_string())?;
    if !ready {
        return Err("preview task is not a ready local task".into());
    }
    tx.execute("CREATE TABLE IF NOT EXISTS task_preview_ports (task_id TEXT NOT NULL REFERENCES tasks(id), port INTEGER NOT NULL CHECK(port BETWEEN 1 AND 65535), PRIMARY KEY(task_id,port))", []).map_err(|e| e.to_string())?;
    tx.execute(
        "INSERT OR IGNORE INTO task_preview_ports(task_id,port) VALUES(?1,?2)",
        params![task_id, port],
    )
    .map_err(|e| e.to_string())?;
    tx.commit().map_err(|e| e.to_string())?;
    Ok(())
}

/// Resolves only a durable, explicitly approved task port to executor loopback.
pub fn target(data_dir: &Path, task_id: &str, port: u16) -> Result<SocketAddr, String> {
    if !safe_task_id(task_id) {
        return Err("preview task id is invalid".into());
    }
    if port == 0 {
        return Err("preview port is invalid".into());
    }
    let conn = config::connection_at(&config::db_path_in(data_dir).map_err(|e| e.to_string())?)
        .map_err(|e| e.to_string())?;
    let allowed: bool = conn.query_row(
        "SELECT EXISTS(SELECT 1 FROM task_preview_ports a JOIN tasks t ON t.id=a.task_id JOIN task_provisioning p ON p.task_id=t.id WHERE a.task_id=?1 AND a.port=?2 AND t.tombstoned_at IS NULL AND p.state='ready')",
        params![task_id, port], |row| row.get(0),
    ).unwrap_or(false);
    if !allowed {
        return Err("preview destination is not approved for this task".into());
    }
    Ok(SocketAddr::new(IpAddr::V4(Ipv4Addr::LOCALHOST), port))
}

pub fn safe_query(query: Option<&str>) -> bool {
    query.is_none()
}

/// Task IDs are generated by Swath and are embedded in peer preview URLs.  Keep this check here
/// as well as at the router so callers cannot turn an approved-port lookup into URL path syntax.
pub fn safe_task_id(task_id: &str) -> bool {
    !task_id.is_empty()
        && task_id.len() <= 128
        && task_id
            .bytes()
            .all(|byte| byte.is_ascii_alphanumeric() || matches!(byte, b'-' | b'_'))
}

pub fn safe_path(path: &str) -> bool {
    if path.is_empty() {
        return true;
    }
    // Reject URL-encoded traversal, Windows drive/UNC paths, and control characters before the
    // route is interpolated into either a local HTTP request or a peer connector URL.
    if path.starts_with('/')
        || path.starts_with("//")
        || path.as_bytes().get(0..3).is_some_and(|prefix| {
            prefix[0].is_ascii_alphabetic() && prefix[1] == b':' && prefix[2] == b'/'
        })
        || path.chars().any(|character| character.is_ascii_control())
    {
        return false;
    }
    path.split('/').all(|part| {
        !part.is_empty()
            && part != "."
            && part != ".."
            && !part.contains(['\\', '?', '#', '%', ':'])
    })
}

#[cfg(test)]
mod tests {
    use super::{approve, safe_path, safe_query, safe_task_id, target};
    use crate::config;
    use std::fs;
    use std::net::{IpAddr, Ipv4Addr};

    #[test]
    fn rejects_proxy_escape_paths() {
        assert!(safe_path("assets/app.js"));
        assert!(!safe_path("../admin"));
        assert!(!safe_path("a/../admin"));
        assert!(!safe_path("a\\b"));
        assert!(!safe_path("a?host=internal"));
        assert!(!safe_path("%2e%2e/admin"));
        assert!(!safe_path("C:/Windows/system.ini"));
        assert!(!safe_path("assets/\u{7f}app.js"));
        assert!(safe_query(None));
        assert!(!safe_query(Some("redirect=http://127.0.0.1")));
        assert!(safe_task_id("task-123"));
        assert!(!safe_task_id("task/123"));
        assert!(!safe_task_id("task?port=1"));
    }

    #[test]
    fn grants_only_live_ready_tasks_and_rechecks_the_fence() {
        let root = std::env::temp_dir().join(format!(
            "swath-preview-policy-{}-{}",
            std::process::id(),
            std::thread::current().name().unwrap_or("test")
        ));
        let _ = fs::remove_dir_all(&root);
        config::initialize(&root).unwrap();
        let conn = config::connection_at(&config::db_path_in(&root).unwrap()).unwrap();
        conn.execute(
            "INSERT INTO networks(id,name,schema_version,revision,created_at) VALUES('network','Network',4,1,0)",
            [],
        )
        .unwrap();
        conn.execute(
            "INSERT INTO projects(id,network_id,name,default_branch,revision,created_at) VALUES('project','network','Project','main',1,0)",
            [],
        )
        .unwrap();
        conn.execute(
            "INSERT INTO tasks(id,project_id,title,assigned_device_id,lifecycle,revision,created_at) VALUES('ready-task','project','Preview','device','active',1,0)",
            [],
        )
        .unwrap();
        conn.execute(
            "INSERT INTO task_provisioning(task_id,base_commit,worktree_path,state,created_at) VALUES('ready-task','HEAD','/tmp/worktree','ready',0)",
            [],
        )
        .unwrap();
        drop(conn);

        approve(&root, "ready-task", 4123).unwrap();
        assert_eq!(
            target(&root, "ready-task", 4123).unwrap().ip(),
            IpAddr::V4(Ipv4Addr::LOCALHOST)
        );
        assert!(approve(&root, "ready/task", 4124).is_err());
        assert!(target(&root, "ready-task", 4124).is_err());

        let conn = config::connection_at(&config::db_path_in(&root).unwrap()).unwrap();
        conn.execute("UPDATE tasks SET tombstoned_at=1 WHERE id='ready-task'", [])
            .unwrap();
        drop(conn);
        assert!(target(&root, "ready-task", 4123).is_err());
        let _ = fs::remove_dir_all(root);
    }
}
